// Config compartida entre el panel de admin y la pantalla de edición de
// registros del usuario. `tabla` es el nombre real de la tabla en la DB
// (coincide con lo que usa el backend para notificaciones y solicitudes
// de edición); `endpoint`/`key` son los usados por las funciones de api.js.
export const sectores = [
  {
    key: 'recepcion',
    label: 'Recepción',
    endpoint: 'recepcion',
    tabla: 'Recepcion',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'codigo', label: 'Código' },
      { key: 'materiaprima', label: 'Materia Prima' },
      { key: 'control1', label: 'Control Transporte' },
      { key: 'control2', label: 'Control Envase' },
      { key: 'control3', label: 'Control Rotulado' },
      { key: 'marca', label: 'Marca' },
      { key: 'proveedor', label: 'Proveedor' },
      { key: 'cant', label: 'Cantidad' },
      { key: 'nroremito', label: 'Nro Remito' },
      { key: 'temp', label: 'Temperatura' },
      { key: 'fechaelaborado', label: 'Fecha Elaborado' },
      { key: 'fechavto', label: 'Fecha Vto.' },
      { key: 'lote', label: 'Lote' },
      { key: 'responsable', label: 'Responsable' },
      { key: 'created_at', label: 'Fecha Creación' },
    ],
    filtros: ['lote', 'materiaprima', 'proveedor', 'nroremito', 'responsable'],
  },
  {
    key: 'semielaborado',
    label: 'Semielaborados',
    endpoint: 'semielaborado',
    tabla: 'Semielaborado',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'codigo', label: 'Código' },
      { key: 'semielaborado', label: 'Semielaborado' },
      { key: 'ingrediente', label: 'Ingrediente' },
      { key: 'lotemateriaprima', label: 'Lote Materia Prima' },
      { key: 'lote', label: 'Lote' },
      { key: 'peso', label: 'Peso' },
      { key: 'fecha', label: 'Fecha' },
      { key: 'observaciones', label: 'Observaciones' },
      { key: 'responsable', label: 'Responsable' },
      { key: 'created_at', label: 'Fecha Creación' },
    ],
    filtros: ['semielaborado', 'ingrediente', 'lote', 'fecha', 'responsable'],
  },
  {
    key: 'production',
    label: 'Producción',
    endpoint: 'production',
    tabla: 'Produccion',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'codigo', label: 'Código' },
      { key: 'producto', label: 'Producto' },
      { key: 'materiaprima', label: 'Materia Prima' },
      { key: 'lote', label: 'Lote' },
      { key: 'planproduccion', label: 'Plan Producción' },
      { key: 'produccion', label: 'Producción' },
      { key: 'pesodescarte', label: 'Peso Descarte' },
      { key: 'observaciones', label: 'Observaciones' },
      { key: 'comentarios', label: 'Comentarios' },
      { key: 'responsable', label: 'Responsable' },
      { key: 'created_at', label: 'Fecha Creación' },
    ],
    filtros: ['lote', 'producto', 'materiaprima', 'responsable'],
  },
  {
    key: 'control-pesado',
    label: 'Control Pesado',
    endpoint: 'control-pesado',
    tabla: 'ControlPesado',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'codigo', label: 'Código' },
      { key: 'producto', label: 'Producto' },
      { key: 'materiaprima', label: 'Materia Prima' },
      { key: 'lotemateriaprima', label: 'Lote Materia Prima' },
      { key: 'peso', label: 'Peso' },
      { key: 'fecha', label: 'Fecha' },
      { key: 'observaciones', label: 'Observaciones' },
      { key: 'responsable', label: 'Responsable' },
      { key: 'created_at', label: 'Fecha Creación' },
    ],
    filtros: ['producto', 'materiaprima', 'fecha', 'responsable'],
  },
  {
    key: 'envasado',
    label: 'Envasado',
    endpoint: 'envasado',
    tabla: 'Envasado',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'codigo', label: 'Código' },
      { key: 'loteprod', label: 'Lote Producción' },
      { key: 'loteenvasado', label: 'Lote Envasado' },
      { key: 'producto', label: 'Producto' },
      { key: 'cantenvases', label: 'Cantidad Envases' },
      { key: 'cantdescarte', label: 'Cantidad Descarte' },
      { key: 'fechaingresopackaging', label: 'Fecha Ingreso Packaging' },
      { key: 'fechaelaboracion', label: 'Fecha de Elaboración' },
      { key: 'observaciones', label: 'Observaciones' },
      { key: 'responsable', label: 'Responsable' },
      { key: 'created_at', label: 'Fecha Creación' },
    ],
    filtros: ['loteprod', 'loteenvasado', 'producto', 'responsable'],
  },
  {
    key: 'expendio',
    label: 'Expendio',
    endpoint: 'expendio',
    tabla: 'Expendio',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'codigo', label: 'Código' },
      { key: 'producto', label: 'Producto' },
      { key: 'lote', label: 'Lote' },
      { key: 'destino', label: 'Destino' },
      { key: 'temptransporte', label: 'Temp. Transporte' },
      {
        key: 'limptransporte',
        label: 'Limpieza Transporte',
        render: (value) => (value === true ? 'Sí' : value === false ? 'No' : '-'),
      },
      { key: 'responsable', label: 'Responsable' },
      { key: 'created_at', label: 'Fecha Creación' },
    ],
    filtros: ['lote', 'producto', 'destino', 'responsable'],
  },
];
